version: '3.7'

services:
  browsersync:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    volumes:
      - ./docs:/src
    command: browser-sync start --server --directory --files "*"