version: '3.7'

services:
  browsersync:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./fullstack-course4/examples:/src/course:ro
      - ./docs/:/src/mystuff:ro
    command: browser-sync start --server --no-open false --directory --files "**/*"
